name: github pages

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [main]  # Set a branch to deploy
    paths:
      - doc/src/hugo/**
      - .github/workflows/gh-pages.yml
      - .vale.ini
      - .github/styles/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Check Docs With Vale
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: doc/src/hugo/content
          fail_on_error: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          cd doc/src/hugo ; \
          hugo --minify -v \
          --baseURL "https://riddl.tech" \
          --printMemoryUsage --noBuildLock

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/src/hugo/public
